import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import type { CDEResult } from './cde-pipeline';

export type PrescriptionPDFInput = {
  clinicName: string;
  clinicLogo: string | null;
  clinicianName: string;
  memberName: string;
  memberAge: number;
  memberMobile: string;
  prescriptionId: string;
  clinicId: string;
  memberId: string;
  cdeResult: CDEResult;
  generatedAt: Date;
};

export type PDFOutput = {
  pdfBase64: string;
  qrCodeBase64: string;
  qrPayload: string;
};

export async function generatePrescriptionPDF(input: PrescriptionPDFInput): Promise<PDFOutput> {
  const eligibleGames = input.cdeResult.eligibility.filter(g => g.verdict === 'eligible');
  const modifiedGames = input.cdeResult.eligibility.filter(
    g => g.verdict === 'modified' || g.verdict === 'capped'
  );
  const blockedGames = input.cdeResult.eligibility.filter(g => g.verdict === 'blocked');

  const qrPayload = JSON.stringify({
    type: 'kriya_prescription',
    prescription_id: input.prescriptionId,
    clinic_id: input.clinicId,
    member_id: input.memberId,
    v: 1,
  });
  const qrCodeBase64 = await QRCode.toDataURL(qrPayload, {
    width: 200,
    margin: 1,
    color: { dark: '#000000', light: '#ffffff' },
  });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 60, right: 60 },
    });
    const chunks: Buffer[] = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => {
      resolve({ pdfBase64: Buffer.concat(chunks).toString('base64'), qrCodeBase64, qrPayload });
    });
    doc.on('error', reject);

    const TEAL = '#0d9488';
    const DARK = '#0f172a';
    const GRAY = '#64748b';

    // Header
    doc.fontSize(20).fillColor(TEAL).text('KRIYA', 60, 50);
    doc.fontSize(9).fillColor(GRAY).text('Movement Health Platform', 60, 73);
    doc.fontSize(14).fillColor(DARK).text(input.clinicName, 60, 95);
    doc.fontSize(9).fillColor(GRAY).text(
      `Prescription Date: ${input.generatedAt.toLocaleDateString('en-IN')}`,
      60, 112
    );

    // Patient block + QR
    doc.moveTo(60, 135).lineTo(535, 135).strokeColor('#e2e8f0').stroke();
    doc.fontSize(10).fillColor(DARK).text(`Patient: ${input.memberName}`, 60, 148);
    doc.text(`Age: ${input.memberAge}`, 60, 163);
    doc.text(`Clinician: ${input.clinicianName}`, 300, 148);

    const qrBuffer = Buffer.from(qrCodeBase64.replace(/^data:image\/png;base64,/, ''), 'base64');
    doc.image(qrBuffer, 450, 148, { width: 80 });
    doc.fontSize(7).fillColor(GRAY).text('Scan to activate Kriya app', 450, 232, {
      width: 80, align: 'center',
    });

    // Clinical Findings
    doc.moveTo(60, 260).lineTo(535, 260).strokeColor('#e2e8f0').stroke();
    doc.fontSize(11).fillColor(TEAL).text('CLINICAL FINDINGS', 60, 272);
    doc.fontSize(9).fillColor(DARK).text(input.cdeResult.prose.findings_prose, 60, 290, { width: 475 });

    // MSK Impression
    doc.fontSize(11).fillColor(TEAL).text('MSK IMPRESSION', 60, doc.y + 15);
    doc.fontSize(9).fillColor(DARK).text(input.cdeResult.prose.impression_prose, 60, doc.y + 5, { width: 475 });

    // Contraindications
    doc.fontSize(11).fillColor('#dc2626').text('CONTRAINDICATIONS', 60, doc.y + 15);
    doc.fontSize(9).fillColor(DARK).text(input.cdeResult.prose.contraindications_prose, 60, doc.y + 5, { width: 475 });

    // Exercise Program
    doc.fontSize(11).fillColor(TEAL).text('PRESCRIBED EXERCISE PROGRAM', 60, doc.y + 15);

    if (eligibleGames.length + modifiedGames.length > 0) {
      doc.fontSize(9).fillColor(DARK);
      for (const g of [...eligibleGames, ...modifiedGames]) {
        const marker = g.verdict === 'eligible' ? '✓' : '~';
        const note = g.modifications ? ` (${g.modifications})` : '';
        doc.text(`${marker} ${g.game_name}${note}`, 70, doc.y + 4);
      }
    }

    if (blockedGames.length > 0) {
      doc.fontSize(10).fillColor('#dc2626').text('Locked until reassessment:', 60, doc.y + 12);
      doc.fontSize(9).fillColor(GRAY);
      for (const g of blockedGames) {
        doc.text(`✗ ${g.game_name} — ${g.reason}`, 70, doc.y + 4);
      }
    }

    // Safety note
    doc.fontSize(9).fillColor(GRAY).text(
      input.cdeResult.prose.safety_note_prose,
      60, doc.y + 20, { width: 475, align: 'center' }
    );

    // Red flag alert
    if (input.cdeResult.treeWalkerOutput.red_flag_alert) {
      doc.fontSize(9).fillColor('#dc2626').text(
        input.cdeResult.treeWalkerOutput.red_flag_alert,
        60, doc.y + 10, { width: 475 }
      );
    }

    // Footer
    doc.fontSize(7).fillColor(GRAY)
      .text(`Prescription ID: ${input.prescriptionId}`, 60, 760)
      .text('This prescription was generated by Kriya and reviewed by the named clinician.', 60, 772)
      .text('It is an assistive tool and does not replace clinical judgment.', 60, 784);

    doc.end();
  });
}
